### ISSUE TITLE
Cannot scroll uitableview while dragging on the section header

### ISSUE THREAD

**Issue by daarkfish** [ennioma/EMAccordionTableViewController#6]
UITableview cannot be scroll when dragging on the section header, tried with _tableView.canCancelContentTouches = YES and _tableView.delaysContentTouches = YES but still the same. It will only scroll when dragging on the expanded cells or holding on the section header.

**Comment by ennioma** [comment]
Hi,
I've released a new version 0.5.1 fixing this issue.

Thank you!
