### ISSUE TITLE
How do i set all the section open?

### ISSUE THREAD

**Issue by hardikamal** [ennioma/EMAccordionTableViewController#7]
Any way to set all section open and let user close accordingly.... Thanks for the nice library

**Comment by ennioma** [comment]
Hi @hardikamal with the latest commit (6da91e2ed6e45186f06e620447e0d2acc77bfc9a) now it's possible to set the initial status of any section through the method:

- (void) addAccordionSection: (EMAccordionSection *) section initiallyOpened:(BOOL)opened;

So in your case you just have to set any section as opened.

**Comment by hardikamal** [comment]
@ennioma  through pods i m getting the old version...please have a check at that....also when i set parallax header the 1st section some time gets invisible while scrolling

**Comment by ennioma** [comment]
Yep I've added it right now.

Could you send me some screenshots to understand the problem ?

Ennio Masi from my iPhone
+39.334.1938388

**Comment by hardikamal** [comment]
@ennioma  i happens in sample and when run on simulator

**Comment by ennioma** [comment]
Sorry @hardikamal I don't find the issue. Try to send me the steps to reproduce it or send me some video/screenshots. Thank you!

PS: now the version 0.5.4 is available through pods.
